databaseChangeLog:
  - logicalFilePath: db/changelog/db.changelog-master.yaml

  - include:
      file: classpath:db/changelog/001-identity.yaml
  - include:
      file: classpath:db/changelog/002-multitenancy.yaml
  - include:
      file: classpath:db/changelog/003-oauth2-authorization-server.yaml
