// Auto-generated by `npm run api:generate` — do not edit manually.
// Run the backend first, then: npm run api:generate

export type paths = Record<string, never>
export type components = Record<string, never>
